### ISSUE TITLE
Implement tests to validate process monitoring.

### ISSUE THREAD

**Issue by stephane-segning** [ADORSYS-GIS/monitor-mind#26]
User Story
- #23

**Comment by bryandino673** [comment]
sir please not really understood sir

**Comment by AssahBismarkabah** [comment]
good day sir @stephane-segning  , i will be working on the test to validate the process monitoring

**Comment by stephane-segning** [comment]
@bryandino673 after the service to implement the functionality described by the related user story is implemented, you'll want to write test to ensure it really works, as expected. TO do it, you'll just write into a notebook file

**Comment by AssahBismarkabah** [comment]
hello sir please i have a question.
for the test process monitoring it involves all the different features such as the cpu usage,disc usage etc so the unit test involve testing all the various processes??
and for hans section on the disc usage monitoring how do they differ sir?

**Comment by AssahBismarkabah** [comment]
hello @stephane-segning good day sir
 i created a pull request some few minutes ago!! for the unit test for validating the process monitoring using the script to track and report the running processes 
please check sir!
