### ISSUE TITLE
Document the setup and usage instructions for the monitoring tool.

### ISSUE THREAD

**Issue by stephane-segning** [ADORSYS-GIS/monitor-mind#42]
User Story
- #41

**Comment by stephane-segning** [comment]
I need more explanation

**Comment by Tekum-Emmanuella** [comment]
sir i want to take this ticket

**Comment by Tekum-Emmanuella** [comment]
Sir i really don't get it. 
How am i to document on the setup and usage instructions when i don't know the tools they used is the codes?.
 Am i to get feedback from the other members?.

**Comment by stephane-segning** [comment]
Yes @Tekum-Emmanuella, you should discuss with the others to write a better documentation.
