### ISSUE TITLE
Write unit tests for the CPU monitoring script

### ISSUE THREAD

**Issue by stephane-segning** [ADORSYS-GIS/monitor-mind#5]
User Story #1 

Write unit tests for the CPU monitoring script.

**Comment by ValantineSuh** [comment]
Sir am not understanding this part well ?

**Comment by stephane-segning** [comment]
When you implement a new feature in a system, you need to test it through and through to show that you understand what you're doing. The code, in the service that you're going to write, in the ticket #4 is the one you should test
